site_name: NOTE
markdown_extensions:
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - footnotes
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

theme:
  name: material
  custom_dir: overrides
  language: zh-TW
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: white
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  icon:
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/git-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - toc.follow
    - content.action.edit
  font:
    text: Noto Serif Simplified Chinese
    code: Roboto Mono
repo_url: https://github.com/rocky-raccoon33/notes
repo_name: rocky-raccoon33/notes
site_author: dinghesheng
edit_uri: notes/blob/main/docs

extra_css:
  - stylesheets/extra.css

plugins:
  - blog:
  - social:
      cards_font: Noto Sans SC
  - search:
      lang: zh
  - git-authors
  - git-committers:
      repository: https://github.com/rocky-raccoon33/notes
