site_name: NOTE
markdown_extensions:
  - md_in_html
  - abbr
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - footnotes
  - tables
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

theme:
  name: material
  language: zh-TW
  favicon: assets/logo.png
  logo: assets/logo.png
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/git-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.indexes
    - navigation.path
    - navigation.instant
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - toc.follow
    - content.action.edit
    - navigation.prune
  font:
    text: Exo 2,Noto Sans Simplified Chinese
    code: Roboto Mono
repo_url: https://github.com/rocky-raccoon33/notes
repo_name: rocky-raccoon33/notes
site_author: Maurice
edit_uri: blob/main/docs

extra_css:
  - stylesheets/extra.css
  - stylesheets/mermaid.min.css

extra:
  generator: false
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

plugins:
  - blog
  - search:
      lang: zh-TW
  - git-authors

extra_javascript:
  - https://unpkg.com/browse/mermaid@9.4.0/dist/mermaid.min.js
